[general]
destination = "$HOME/.config/hypr/conf/monitor.conf"

[power_events]

[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_AC0"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_AC0"

## LAPTOP-ONLY-BAT
[profiles.laptop-only-bat]
config_file = "hyprconfigs/laptop-only-bat.conf"
config_file_type = "static"

[profiles.laptop-only-bat.conditions]
power_state = "BAT"
lid_state = "Opened"

[[profiles.laptop-only-bat.conditions.required_monitors]]
name = "eDP-1"
description = "Chimei Innolux Corporation 0x1521"
monitor_tag = "monitor0"

## MONITOR-ONLY-BAT
[profiles.monitor-only-bat]
config_file = "hyprconfigs/monitor-only-bat.conf"
config_file_type = "static"

[profiles.monitor-only-bat.conditions]
power_state = "BAT"
lid_state = "Closed"

[[profiles.monitor-only-bat.conditions.required_monitors]]
name = "DP-1"
description = "Lenovo Group Limited R27q-30 U533MLPB"
monitor_tag = "monitor1"

## MONITOR-ONLY-AC
[profiles.monitor-only-ac]
config_file = "hyprconfigs/monitor-only-ac.conf"
config_file_type = "static"

[profiles.monitor-only-ac.conditions]
power_state = "AC"
lid_state = "Closed"

[[profiles.laptop-only-ac.conditions.required_monitors]]
name = "DP-1"
description = "Lenovo Group Limited R27q-30 U533MLPB"
monitor_tag = "monitor1"

## LAPTOP-ONLY-AC
[profiles.laptop-only-ac]
config_file = "hyprconfigs/laptop-only-ac.conf"
config_file_type = "static"

[profiles.laptop-only-ac.conditions]
power_state = "AC"
lid_state = "Opened"

[[profiles.monitor-only-ac.conditions.required_monitors]]
name = "eDP-1"
description = "Chimei Innolux Corporation 0x1521"
monitor_tag = "monitor0"

[fallback_profile]
config_file = "hyprconfigs/fallback.conf"
config_file_type = "static"
