"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled=true

[character] 
success_symbol = '[âœ](#a89982) '

[directory]
format = "[$path](yellow) "

[localip]
ssh_only = false
format = '[@$localipv4](#5f5f5f) '
disabled = true

[cmd_duration]
min_time = 2000 
format = " took [$duration]($style)"

[git_branch]
format = '[\($branch\)](#98971a) '

[git_status]
conflicted = "âš”ï¸"
untracked = "âŒ"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ—ƒï¸"
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸"
format = "[$all_status]($style) "

[git_commit]
commit_hash_length = 8
style = "bold white"
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[hostname]
ssh_only = true 
format = "[$hostname](#bdae93) "
trim_at = "-"
style = "dimmed gray"
disabled = false

[memory_usage]
format = "[$symbol $ram](#bdae93)"
threshold = 20
symbol = "ó°†¼"
disabled = true

[package]
disabled = true

[lua]
disabled = true

[python]
format = "[(\\($virtualenv\\) )]($style)"
disabled = false

[rust]
format = "[$symbol$version]($style) "
style = "bold green"
disabled = true

[username]
disabled = true

[nodejs]
format = "[$symbol$version](green)"
symbol = " â¬¢ "
version_format = "v${major}"
disabled = true